version: "3"
services:
  web:
    build: .
    environment:
      - NODE_ENV=development
      - MYSQL_DATABASE_URL=mysql://admin:admin@db:3306/resizer_db
      - REDIS_URL=redis://redis:6379
    ports:
      - 1337:1337
    command: "npm run dev"
    volumes:
      - .:/usr/src/app
    container_name: sails_container
  db:
    image: mysql:5.7
    volumes:
        - db_data:/var/lib/mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=admin,
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=resizer_db
    container_name: mysql
  redis:
    image: redis
    container_name: resizer-boilerplate_redis_1
volumes:
  db_data: